### ISSUE TITLE
Base64 encode function doesn’t work

### ISSUE THREAD

**Issue by u546342** [defold/extension-crypt#2]
Hello
Function crypt.encode_base64 doesn’t work. It always return nil.
Defold version 1.2.187.

```
print(crypt.encode_base64("hello world"))
> DEBUG:SCRIPT: nil
```

**Comment by JCash** [comment]
Thanks for the report!
Yes, that seems indeed odd.
My guess is that we calculate too little space for the destination buffer:
https://github.com/defold/extension-crypt/blob/master/crypt/src/crypt.cpp#L79-L86

**Comment by britzl** [comment]
> My guess is that we calculate too little space for the destination buffer

Correct. The length calculation wasn't correct. Fixed in this commit: https://github.com/defold/extension-crypt/commit/37d36fa55f50399bb521e135ca0fc681fd05223b
